### ISSUE TITLE
Error with Codacy

### ISSUE THREAD

**Issue by Incrested** [Commit451/skyhook#109]
Upon setting it up, I get this error:
```
Error: "TypeError: Cannot read property 'data' of undefined\n at Codacy.<anonymous> (/app/dist/provider/Codacy.js:25:42)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Codacy.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Codacy.js:2:12)\n at Codacy.parseData (/app/dist/provider/Codacy.js:21:16)\n at Codacy.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:6:71\n at new Promise (<anonymous>)"
```

I'm going to try to also help and see if I can find a resolution and make a pull request regarding it.

**Comment by Incrested** [comment]
Fixed it myself. I seemed to have been using the wrong type of integration.
