### ISSUE TITLE
Deleting a tag causing Skyhook error

### ISSUE THREAD

**Issue by adamjseitz** [Commit451/skyhook#127]
* Provider: Gitlab

When I delete a tag, as follows...

```
git tag -d 12345
git push origin :refs/tags/12345
```

...this error is produced:

```
Error: "TypeError: Cannot read property 'length' of null
 at GitLab.<anonymous> (/app/dist/provider/GitLab.js:80:103)
 at Generator.next (<anonymous>)
 at /app/dist/provider/GitLab.js:6:71
 at new Promise (<anonymous>)
 at __awaiter (/app/dist/provider/GitLab.js:2:12)
 at GitLab.tagPush (/app/dist/provider/GitLab.js:72:16)
 at GitLab.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)
 at Generator.next (<anonymous>)
 at fulfilled (/app/dist/provider/BaseProvider.js:3:58)
 at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by Cairo2k18** [comment]
I am having this same issue

**Comment by dscalzi** [comment]
Is this still an issue?

**Comment by adamjseitz** [comment]
Yes, it seems to still be an issue. Here's an updated traceback (just looks like some line numbers changed):

```
Error: "TypeError: Cannot read property 'length' of null
 at GitLab.<anonymous> (/app/dist/provider/GitLab.js:81:103)
 at Generator.next (<anonymous>)
 at /app/dist/provider/GitLab.js:7:71
 at new Promise (<anonymous>)
 at __awaiter (/app/dist/provider/GitLab.js:3:12)
 at GitLab.tagPush (/app/dist/provider/GitLab.js:73:16)
 at GitLab.<anonymous> (/app/dist/provider/BaseProvider.js:58:33)
 at Generator.next (<anonymous>)
 at fulfilled (/app/dist/provider/BaseProvider.js:4:58)
 at process._tickCallback (internal/process/next_tick.js:68:7)"
```
