### ISSUE TITLE
[GitLab] Skyhook errors when deleting a tag

### ISSUE THREAD

**Issue by Cairo2k18** [Commit451/skyhook#134]
I received this error;

```
Error: "TypeError: Cannot read property 'length' of null\n at GitLab.<anonymous> (/app/dist/provider/GitLab.js:80:103)\n at Generator.next (<anonymous>)\n at /app/dist/provider/GitLab.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/GitLab.js:2:12)\n at GitLab.tagPush (/app/dist/provider/GitLab.js:72:16)\n at GitLab.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by Cairo2k18** [comment]
Nevermind.. duplicate of #127
