### ISSUE TITLE
Skyhook error when pushing to BitBucket

### ISSUE THREAD

**Issue by marth8880** [Commit451/skyhook#141]
There is an error when pushing to repository on BitBucket:

```
An error has occured on skyhook for your webhook with provider bitbucket. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'length' of undefined\n at BitBucket.<anonymous> (/app/dist/provider/Bitbucket.js:77:103)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Bitbucket.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Bitbucket.js:3:12)\n at BitBucket.repoPush (/app/dist/provider/Bitbucket.js:49:16)\n at BitBucket.<anonymous> (/app/dist/provider/BaseProvider.js:58:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:4:58)\n at processTicksAndRejections (internal/process/task_queues.js:88:5)"
```

Webhook setup:

![image](https://user-images.githubusercontent.com/12036256/79007993-557dd280-7b54-11ea-8702-debbc8d12e8b.png)

Webhook plugin is "Post Webhooks for Bitbucket" by Move Work Forward.

**Comment by wdhodges** [comment]
Are you using Bitbucket Server or Bitbucket Cloud?

**Comment by marth8880** [comment]
I am using Bitbucket Server.

**Comment by wdhodges** [comment]
Skyhook doesn’t support Bitbucket server just yet
