### ISSUE TITLE
HTTP 429 when sending Bitbucket payloads

### ISSUE THREAD

**Issue by neon-dev** [Commit451/skyhook#153]
```
Error: Request failed with status code 429
    at createError (/rbd/pnpm-volume/90fb9114-add2-4467-b406-16062c42fe85/node_modules/.registry.npmjs.org/axios/0.19.2/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/rbd/pnpm-volume/90fb9114-add2-4467-b406-16062c42fe85/node_modules/.registry.npmjs.org/axios/0.19.2/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/rbd/pnpm-volume/90fb9114-add2-4467-b406-16062c42fe85/node_modules/.registry.npmjs.org/axios/0.19.2/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17)
```
I've activated Bitbucket's webhook logging and it's definitely not spamming. Only one push event every few hours.

**Comment by neon-dev** [comment]
It suddenly started to work again by itself. In case you fixed it: thank you.
