### ISSUE TITLE
Heroku Skyhook Error Sent to Discord

### ISSUE THREAD

**Issue by bipolarmorgan** [Commit451/skyhook#166]
**Skyhook Error**

`An error has occured on skyhook for your webhook with provider heroku. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'event' of undefined\n at Heroku.<anonymous> (/workspace/dist/provider/Heroku.js:31:73)\n at Generator.next (<anonymous>)\n at /workspace/dist/provider/Heroku.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/workspace/dist/provider/Heroku.js:3:12)\n at Heroku.parseData (/workspace/dist/provider/Heroku.js:27:16)\n at Heroku.<anonymous> (/workspace/dist/provider/BaseProvider.js:72:33)\n at Generator.next (<anonymous>)\n at /workspace/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"`

_______________________________________________________________

I hope that helps, if you need further info, just let me know. Thanks!

**Comment by bipolarmorgan** [comment]
how do i turn this off?? it keeps erroring
