### ISSUE TITLE
Rollbar error

### ISSUE THREAD

**Issue by VladimirAfanasievFS** [Commit451/skyhook#206]
[Skyhook Error](https://github.com/Commit451/skyhook/issues)
An error has occured on skyhook for your webhook with provider rollbar. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read properties of null (reading 'embeds')\n at Rollbar.addEmbed (file:///workspace/dist/provider/BaseProvider.js:74:26)\n at Rollbar.postParse (file:///workspace/dist/provider/Rollbar.js:64:14)\n at Rollbar.parse (file:///workspace/dist/provider/BaseProvider.js:43:14)\n at file:///workspace/dist/index.js:127:45\n at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)\n at next (/workspace/node_modules/express/lib/router/route.js:144:13)\n at Route.dispatch (/workspace/node_modules/express/lib/router/route.js:114:3)\n at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)\n at /workspace/node_modules/express/lib/router/index.js:284:15\n at param (/workspace/node_modules/express/lib/router/index.js:365:14)"

**Comment by alejsalaz** [comment]
Same thing over here:

![image](https://github.com/Commit451/skyhook/assets/86681635/85969cd3-d2bb-4407-b40c-80fae4dbe653)
