### ISSUE TITLE
UnsupportedMediaTypeError

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#57]
This keeps popping up in the logs
```
error: UnsupportedMediaTypeError: unsupported content encoding "utf-8"
2:21 AM
    at contentstream (/app/node_modules/body-parser/lib/read.js:170:13)
2:21 AM
    at read (/app/node_modules/body-parser/lib/read.js:54:14)
2:21 AM
    at jsonParser (/app/node_modules/body-parser/lib/types/json.js:127:5)
2:21 AM
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2:21 AM
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2:21 AM
    at /app/node_modules/express/lib/router/index.js:284:7
2:21 AM
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2:21 AM
    at next (/app/node_modules/express/lib/router/index.js:275:10)
2:21 AM
    at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
2:21 AM
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by Jawnnypoo** [comment]
Looks like this may be the solution
https://github.com/expressjs/body-parser/issues/76

**Comment by dscalzi** [comment]
Any update on this?

**Comment by Jawnnypoo** [comment]
Not really seeing this anymore, I'll close for now
