### ISSUE TITLE
Bitbucket body not defined

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#60]
[Thu, 26 Oct 2017 20:39:32 GMT] Calling pullrequestCreated() in BitBucket provider.
3:39 PM
Error during parse: ReferenceError: body is not defined
3:39 PM
    at BitBucket.pullrequestCreated (/app/providers/bitbucket.js:284:26)
3:39 PM
    at BitBucket.parse (/app/util/BaseProvider.js:21:29)
3:39 PM
    at <anonymous>
3:39 PM
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by Jawnnypoo** [comment]
Noice
