### ISSUE TITLE
Unity share_url not defined

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#61]
[Thu, 26 Oct 2017 20:39:22 GMT] Calling parseData() in Unity provider.
3:39 PM
Error during parse: TypeError: Cannot read property 'share_url' of undefined
3:39 PM
    at Unity.parseData (/app/providers/unity.js:17:38)
3:39 PM
    at Unity.parse (/app/util/BaseProvider.js:21:29)
3:39 PM
    at /app/server.js:82:45
3:39 PM
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
3:39 PM
    at next (/app/node_modules/express/lib/router/route.js:137:13)
3:39 PM
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
3:39 PM
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
3:39 PM
    at /app/node_modules/express/lib/router/index.js:281:22
3:39 PM
    at param (/app/node_modules/express/lib/router/index.js:354:14)
3:39 PM
    at param (/app/node_modules/express/lib/router/index.js:365:14)

**Comment by dscalzi** [comment]
Not sure about this one, didn't write the unity provider.
