### ISSUE TITLE
GitLab push() replace error

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#62]
[Thu, 26 Oct 2017 21:00:26 GMT] Calling push() in GitLab provider.
4:00 PM
Error during parse: TypeError: Cannot read property 'replace' of undefined
4:00 PM
    at Function.formatType (/app/util/BaseProvider.js:28:20)
4:00 PM
    at GitLab.parse (/app/util/BaseProvider.js:17:29)
4:00 PM
    at <anonymous>
4:00 PM
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by Jawnnypoo** [comment]
I think I fixed this one? We will see
