### ISSUE TITLE
Unity error

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#63]
[Fri, 27 Oct 2017 01:30:58 GMT] Calling parseData() in Unity provider.
8:30 PM
Error during parse: TypeError: Cannot read property 'href' of undefined
8:30 PM
    at Unity.parseData (/app/providers/unity.js:33:37)
8:30 PM
    at Unity.parse (/app/util/BaseProvider.js:27:29)
8:30 PM
    at /app/server.js:82:45
8:30 PM
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
8:30 PM
    at next (/app/node_modules/express/lib/router/route.js:137:13)
8:30 PM
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
8:30 PM
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
8:30 PM
    at /app/node_modules/express/lib/router/index.js:281:22
8:30 PM
    at param (/app/node_modules/express/lib/router/index.js:354:14)
8:30 PM
    at param (/app/node_modules/express/lib/router/index.js:365:14)

**Comment by dscalzi** [comment]
It's possible unity changed their payload format

**Comment by dscalzi** [comment]
Any update on this?

**Comment by Jawnnypoo** [comment]
I haven't seen it come through in a while, closing
