### ISSUE TITLE
GitLab error

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#68]
Error during parse: TypeError: Cannot read property 'replace' of undefined
9:48 PM
    at Function.formatType (/app/util/BaseProvider.js:7:20)
9:48 PM
    at GitLab.parse (/app/util/BaseProvider.js:23:29)
9:48 PM
    at <anonymous>
9:48 PM
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by dscalzi** [comment]
Resolved by 8edf1dba5142def8331b95f2573edd2200c07a31 - null === undefined is false, null == undefined is true. Always use loose equals for null checks ;)
